plugins {
    id 'com.github.hierynomus.license' version '0.16.1'
}

defaultTasks 'shadowJar'

version '0.25.0-SNAPSHOT'

subprojects {
    version = rootProject.version
    group = 'xyz.kyngs.librelogin'

    apply plugin: 'com.github.hierynomus.license'

    repositories {
        mavenLocal()
        mavenCentral()

        maven {
            url 'https://jitpack.io'
        }
    }

    license {
        header = rootProject.file('HEADER.txt')
        include '**/*.java'
        exclude '**/protocollib/EncryptionUtil.java'
    }

}
